version: "3.8"

services:
  watch-together:
    build: .
    ports:
      - "8000:8000"
    container_name: watch-together
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:6-alpine
    container_name: watch-redis
    ports:
      - "6379:6379"
    restart: always
