version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis  # Tell the Flask app to connect to the 'redis' service
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"